/**
 * Organizations data generated from Airtable
 *
 * Generated: 2026-01-04T20:48:09.577Z
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * To update:
 * 1. Edit the "Organizations" table in Airtable
 * 2. Check the "Sponsor" field for organizations that should display as sponsors
 * 3. Run: npm run generate-organizations
 * 4. Review changes and commit
 *
 * Logos are automatically uploaded to Firebase Storage for permanent URLs.
 */

// All sponsors (organizations with Sponsor checked, sorted by tier then order)
export const sponsors = [
  {
    "id": "recJSw5hM0bomWA7O",
    "name": "Knight Foundation",
    "slug": "knight-foundation",
    "website": "https://knightfoundation.org/",
    "logoUrl": "https://storage.googleapis.com/cjs2026.firebasestorage.app/sponsor-logos/knight-foundation.png",
    "localLogoPath": "/sponsor-logos/knight-foundation.png",
    "isSponsor": true,
    "sponsorTier": "presenting sponsor",
    "sponsorOrder": 999,
    "description": "",
    "type": "organization",
    "visible": true
  }
];

// Sponsors grouped by tier
export const sponsorsByTier = {
  "presenting sponsor": [
    {
      "id": "recJSw5hM0bomWA7O",
      "name": "Knight Foundation",
      "slug": "knight-foundation",
      "website": "https://knightfoundation.org/",
      "logoUrl": "https://storage.googleapis.com/cjs2026.firebasestorage.app/sponsor-logos/knight-foundation.png",
      "localLogoPath": "/sponsor-logos/knight-foundation.png",
      "isSponsor": true,
      "sponsorTier": "presenting sponsor",
      "sponsorOrder": 999,
      "description": "",
      "type": "organization",
      "visible": true
    }
  ]
};

// All organizations (visible ones)
export const organizations = [
  {
    "id": "recJSw5hM0bomWA7O",
    "name": "Knight Foundation",
    "slug": "knight-foundation",
    "website": "https://knightfoundation.org/",
    "logoUrl": "https://storage.googleapis.com/cjs2026.firebasestorage.app/sponsor-logos/knight-foundation.png",
    "localLogoPath": "/sponsor-logos/knight-foundation.png",
    "isSponsor": true,
    "sponsorTier": "presenting sponsor",
    "sponsorOrder": 999,
    "description": "",
    "type": "organization",
    "visible": true
  }
];

// Helper function to get sponsor by ID
export function getSponsorById(id) {
  return sponsors.find(s => s.id === id) || null;
}

// Helper function to get sponsors by tier
export function getSponsorsByTier(tier) {
  return sponsorsByTier[tier?.toLowerCase()] || [];
}

// Check if there are any sponsors
export function hasSponsors() {
  return sponsors.length > 0;
}

// Get all unique sponsor tiers
export function getSponsorTiers() {
  return Object.keys(sponsorsByTier);
}

// Tier display names
export const tierDisplayNames = {
  presenting: 'Presenting sponsor',
  'presenting sponsor': 'Presenting sponsor',
  lead: 'Lead sponsors',
  'lead sponsor': 'Lead sponsors',
  supporting: 'Supporting sponsors',
  'supporting sponsor': 'Supporting sponsors',
  partner: 'Partners',
  media: 'Media partners',
  'media partner': 'Media partners',
  community: 'Community partners',
  'community partner': 'Community partners',
};

// Generation metadata
export const metadata = {
  generatedAt: '2026-01-04T20:48:09.577Z',
  totalOrganizations: 1,
  totalSponsors: 1,
  tiers: ["presenting sponsor"],
};

export default {
  sponsors,
  sponsorsByTier,
  organizations,
  getSponsorById,
  getSponsorsByTier,
  hasSponsors,
  getSponsorTiers,
  tierDisplayNames,
  metadata
};
