/**
 * Organizations data generated from Airtable
 *
 * Generated: 2025-12-17T21:56:23.051Z
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * To update:
 * 1. Edit the "Organizations" table in Airtable
 * 2. Check the "Sponsor" field for organizations that should display as sponsors
 * 3. Run: npm run generate-organizations
 * 4. Review changes and commit
 */

// All sponsors (organizations with Sponsor checked, sorted by tier then order)
export const sponsors = [
  {
    "id": "recJSw5hM0bomWA7O",
    "name": "Knight Foundation",
    "slug": "knight-foundation",
    "website": "https://knightfoundation.org/",
    "logoUrl": "https://v5.airtableusercontent.com/v3/u/48/48/1766016000000/SknQHOb-WuSKrSVfZ_e3UQ/nsTokbGy6t0OnEpBz1H6rGUEhMRjiVHYX1_hVnwrGVN0XslnRVrKB3bo3BpoVkTKtjsNOJZf-Xp-w2_lgApBR0WcCuYM1B_tE9K4OamNy_NmSbIi_Aj5Ls6iCX9I3KtwNqUsMpq7DlS4oC68ZzSxEL5NaR3m9tfZlR26CZLFBB0/2AG8wHJ_rSC1eTmX9jM6tl5azU67fYrSrGFBAs4VV1E",
    "localLogoPath": "/sponsor-logos/knight-foundation.png",
    "isSponsor": true,
    "sponsorTier": "presenting sponsor",
    "sponsorOrder": 999,
    "description": "",
    "type": "organization",
    "visible": true
  }
];

// Sponsors grouped by tier
export const sponsorsByTier = {
  "presenting sponsor": [
    {
      "id": "recJSw5hM0bomWA7O",
      "name": "Knight Foundation",
      "slug": "knight-foundation",
      "website": "https://knightfoundation.org/",
      "logoUrl": "https://v5.airtableusercontent.com/v3/u/48/48/1766016000000/SknQHOb-WuSKrSVfZ_e3UQ/nsTokbGy6t0OnEpBz1H6rGUEhMRjiVHYX1_hVnwrGVN0XslnRVrKB3bo3BpoVkTKtjsNOJZf-Xp-w2_lgApBR0WcCuYM1B_tE9K4OamNy_NmSbIi_Aj5Ls6iCX9I3KtwNqUsMpq7DlS4oC68ZzSxEL5NaR3m9tfZlR26CZLFBB0/2AG8wHJ_rSC1eTmX9jM6tl5azU67fYrSrGFBAs4VV1E",
      "localLogoPath": "/sponsor-logos/knight-foundation.png",
      "isSponsor": true,
      "sponsorTier": "presenting sponsor",
      "sponsorOrder": 999,
      "description": "",
      "type": "organization",
      "visible": true
    }
  ]
};

// All organizations (visible ones)
export const organizations = [
  {
    "id": "recJSw5hM0bomWA7O",
    "name": "Knight Foundation",
    "slug": "knight-foundation",
    "website": "https://knightfoundation.org/",
    "logoUrl": "https://v5.airtableusercontent.com/v3/u/48/48/1766016000000/SknQHOb-WuSKrSVfZ_e3UQ/nsTokbGy6t0OnEpBz1H6rGUEhMRjiVHYX1_hVnwrGVN0XslnRVrKB3bo3BpoVkTKtjsNOJZf-Xp-w2_lgApBR0WcCuYM1B_tE9K4OamNy_NmSbIi_Aj5Ls6iCX9I3KtwNqUsMpq7DlS4oC68ZzSxEL5NaR3m9tfZlR26CZLFBB0/2AG8wHJ_rSC1eTmX9jM6tl5azU67fYrSrGFBAs4VV1E",
    "localLogoPath": "/sponsor-logos/knight-foundation.png",
    "isSponsor": true,
    "sponsorTier": "presenting sponsor",
    "sponsorOrder": 999,
    "description": "",
    "type": "organization",
    "visible": true
  }
];

// Helper function to get sponsor by ID
export function getSponsorById(id) {
  return sponsors.find(s => s.id === id) || null;
}

// Helper function to get sponsors by tier
export function getSponsorsByTier(tier) {
  return sponsorsByTier[tier?.toLowerCase()] || [];
}

// Check if there are any sponsors
export function hasSponsors() {
  return sponsors.length > 0;
}

// Get all unique sponsor tiers
export function getSponsorTiers() {
  return Object.keys(sponsorsByTier);
}

// Tier display names
export const tierDisplayNames = {
  presenting: 'Presenting sponsor',
  lead: 'Lead sponsors',
  supporting: 'Supporting sponsors',
  partner: 'Partners',
  media: 'Media partners',
  community: 'Community partners',
};

// Generation metadata
export const metadata = {
  generatedAt: '2025-12-17T21:56:23.051Z',
  totalOrganizations: 1,
  totalSponsors: 1,
  tiers: ["presenting sponsor"],
};

export default {
  sponsors,
  sponsorsByTier,
  organizations,
  getSponsorById,
  getSponsorsByTier,
  hasSponsors,
  getSponsorTiers,
  tierDisplayNames,
  metadata
};
