/**
 * Schedule data generated from Airtable
 *
 * Generated: 2026-01-04T20:47:52.037Z
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * To update:
 * 1. Edit the "Schedule" table in Airtable
 * 2. Run: npm run generate-schedule
 * 3. Review changes and commit
 */

// All sessions (sorted by day, then order)
export const sessions = [
  {
    "id": "monday-session-1",
    "airtableId": "recFbzRyQytMTYBi9",
    "title": "Blue Engine coaching from Hub/how to build revenue for collaboratives",
    "description": "Explore effective strategies for building sustainable revenue streams within collaborative organizations as Joe Amditis shares insights from the Blue Engine coaching model. Attendees will gain practical guidance on leveraging coaching frameworks and innovative approaches to enhance financial stability and growth for collaboratives, with actionable takeaways to implement in their own organizations.",
    "day": "Monday",
    "startTime": "2026-06-08T20:30:00.000Z",
    "endTime": "",
    "type": "session",
    "track": null,
    "room": "",
    "speakers": "Joe Amditis",
    "speakerOrgs": "",
    "isBookmarkable": true,
    "order": 1,
    "visible": true,
    "color": "teal"
  },
  {
    "id": "tuesday-session-2",
    "airtableId": "reczl9QPPVVbX2HLz",
    "title": "Community impact tracking framework from Hub",
    "description": "Explore the innovative community impact tracking framework developed by Hub as Joe Amditis delves into practical strategies for measuring and demonstrating the real-world effects of community initiatives. Attendees will gain valuable insights into effective data collection, analysis, and reporting methods, empowering them to better assess and communicate the outcomes of their own programs. This session is ideal for professionals seeking actionable tools to enhance transparency and accountability in community-driven projects.",
    "day": "Tuesday",
    "startTime": "2026-06-09T15:30:00.000Z",
    "endTime": "",
    "type": "keynote",
    "track": null,
    "room": "",
    "speakers": "Joe Amditis",
    "speakerOrgs": "",
    "isBookmarkable": true,
    "order": 2,
    "visible": true,
    "color": "teal"
  }
];

// Sessions grouped by day
export const sessionsByDay = {
  "monday": [
    {
      "id": "monday-session-1",
      "airtableId": "recFbzRyQytMTYBi9",
      "title": "Blue Engine coaching from Hub/how to build revenue for collaboratives",
      "description": "Explore effective strategies for building sustainable revenue streams within collaborative organizations as Joe Amditis shares insights from the Blue Engine coaching model. Attendees will gain practical guidance on leveraging coaching frameworks and innovative approaches to enhance financial stability and growth for collaboratives, with actionable takeaways to implement in their own organizations.",
      "day": "Monday",
      "startTime": "2026-06-08T20:30:00.000Z",
      "endTime": "",
      "type": "session",
      "track": null,
      "room": "",
      "speakers": "Joe Amditis",
      "speakerOrgs": "",
      "isBookmarkable": true,
      "order": 1,
      "visible": true,
      "color": "teal"
    }
  ],
  "tuesday": [
    {
      "id": "tuesday-session-2",
      "airtableId": "reczl9QPPVVbX2HLz",
      "title": "Community impact tracking framework from Hub",
      "description": "Explore the innovative community impact tracking framework developed by Hub as Joe Amditis delves into practical strategies for measuring and demonstrating the real-world effects of community initiatives. Attendees will gain valuable insights into effective data collection, analysis, and reporting methods, empowering them to better assess and communicate the outcomes of their own programs. This session is ideal for professionals seeking actionable tools to enhance transparency and accountability in community-driven projects.",
      "day": "Tuesday",
      "startTime": "2026-06-09T15:30:00.000Z",
      "endTime": "",
      "type": "keynote",
      "track": null,
      "room": "",
      "speakers": "Joe Amditis",
      "speakerOrgs": "",
      "isBookmarkable": true,
      "order": 2,
      "visible": true,
      "color": "teal"
    }
  ]
};

// Available session types for filtering
export const sessionTypes = [
  "session",
  "keynote"
];

// Available tracks for filtering
export const sessionTracks = [];

// Helper function to get a session by ID
export function getSessionById(id) {
  return sessions.find(s => s.id === id) || null;
}

// Helper function to get multiple sessions by IDs
export function getSessionsByIds(ids) {
  return ids.map(id => getSessionById(id)).filter(Boolean);
}

// Helper function to get bookmarkable sessions only
export function getBookmarkableSessions() {
  return sessions.filter(s => s.isBookmarkable);
}

// Type colors mapping
export const typeColors = {
  session: { bg: 'bg-brand-teal/5', text: 'text-brand-teal', border: 'border-brand-teal/20' },
  workshop: { bg: 'bg-brand-cardinal/5', text: 'text-brand-cardinal', border: 'border-brand-cardinal/20' },
  break: { bg: 'bg-brand-cream', text: 'text-brand-ink-muted', border: 'border-brand-ink/10' },
  special: { bg: 'bg-brand-green-dark/5', text: 'text-brand-green-dark', border: 'border-brand-green-dark/20' },
  lightning: { bg: 'bg-brand-gold/10', text: 'text-brand-gold', border: 'border-brand-gold/20' },
};

// Generation metadata
export const metadata = {
  generatedAt: '2026-01-04T20:47:52.037Z',
  totalSessions: 2,
  mondaySessions: 1,
  tuesdaySessions: 1,
};

export default {
  sessions,
  sessionsByDay,
  sessionTypes,
  sessionTracks,
  getSessionById,
  getSessionsByIds,
  getBookmarkableSessions,
  typeColors,
  metadata
};
