/**
 * Schedule data generated from Airtable
 *
 * Generated: 2025-12-15T19:11:43.902Z
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * To update:
 * 1. Edit the "Schedule" table in Airtable
 * 2. Run: npm run generate-schedule
 * 3. Review changes and commit
 */

// All sessions (sorted by day, then order)
export const sessions = [
  {
    "id": "unknown-session-4",
    "airtableId": "rec5fyPCzXGmTzWOi",
    "title": "Collaborator Q+A connection?",
    "description": "",
    "day": "Monday",
    "startTime": "",
    "endTime": "",
    "type": "session",
    "track": null,
    "room": "",
    "speakers": "",
    "speakerOrgs": "",
    "isBookmarkable": true,
    "order": 4,
    "visible": true,
    "color": "teal"
  },
  {
    "id": "unknown-session-17",
    "airtableId": "recQQB4MMoYONgXpW",
    "title": "How collaboratives can write grant proposals",
    "description": "",
    "day": "Monday",
    "startTime": "",
    "endTime": "",
    "type": "workshop",
    "track": null,
    "room": "",
    "speakers": "",
    "speakerOrgs": "",
    "isBookmarkable": true,
    "order": 17,
    "visible": true,
    "color": "teal"
  },
  {
    "id": "unknown-session-23",
    "airtableId": "reccoAF9gS7LkUkdA",
    "title": "Blue Engine coaching from Hub/how to build revenue for collaboratives",
    "description": "",
    "day": "Monday",
    "startTime": "",
    "endTime": "",
    "type": "plenary",
    "track": null,
    "room": "",
    "speakers": "",
    "speakerOrgs": "",
    "isBookmarkable": true,
    "order": 23,
    "visible": true,
    "color": "teal"
  },
  {
    "id": "unknown-session-29",
    "airtableId": "recyKLDsNT0MMLr0l",
    "title": "Fundraising strategies for collaboratives (maybe lead by Salt Lake)",
    "description": "",
    "day": "Monday",
    "startTime": "",
    "endTime": "",
    "type": "session",
    "track": null,
    "room": "",
    "speakers": "",
    "speakerOrgs": "",
    "isBookmarkable": true,
    "order": 29,
    "visible": true,
    "color": "teal"
  }
];

// Sessions grouped by day
export const sessionsByDay = {
  "monday": [
    {
      "id": "unknown-session-4",
      "airtableId": "rec5fyPCzXGmTzWOi",
      "title": "Collaborator Q+A connection?",
      "description": "",
      "day": "Monday",
      "startTime": "",
      "endTime": "",
      "type": "session",
      "track": null,
      "room": "",
      "speakers": "",
      "speakerOrgs": "",
      "isBookmarkable": true,
      "order": 4,
      "visible": true,
      "color": "teal"
    },
    {
      "id": "unknown-session-17",
      "airtableId": "recQQB4MMoYONgXpW",
      "title": "How collaboratives can write grant proposals",
      "description": "",
      "day": "Monday",
      "startTime": "",
      "endTime": "",
      "type": "workshop",
      "track": null,
      "room": "",
      "speakers": "",
      "speakerOrgs": "",
      "isBookmarkable": true,
      "order": 17,
      "visible": true,
      "color": "teal"
    },
    {
      "id": "unknown-session-23",
      "airtableId": "reccoAF9gS7LkUkdA",
      "title": "Blue Engine coaching from Hub/how to build revenue for collaboratives",
      "description": "",
      "day": "Monday",
      "startTime": "",
      "endTime": "",
      "type": "plenary",
      "track": null,
      "room": "",
      "speakers": "",
      "speakerOrgs": "",
      "isBookmarkable": true,
      "order": 23,
      "visible": true,
      "color": "teal"
    },
    {
      "id": "unknown-session-29",
      "airtableId": "recyKLDsNT0MMLr0l",
      "title": "Fundraising strategies for collaboratives (maybe lead by Salt Lake)",
      "description": "",
      "day": "Monday",
      "startTime": "",
      "endTime": "",
      "type": "session",
      "track": null,
      "room": "",
      "speakers": "",
      "speakerOrgs": "",
      "isBookmarkable": true,
      "order": 29,
      "visible": true,
      "color": "teal"
    }
  ],
  "tuesday": []
};

// Available session types for filtering
export const sessionTypes = [
  "session",
  "workshop",
  "plenary"
];

// Available tracks for filtering
export const sessionTracks = [];

// Helper function to get a session by ID
export function getSessionById(id) {
  return sessions.find(s => s.id === id) || null;
}

// Helper function to get multiple sessions by IDs
export function getSessionsByIds(ids) {
  return ids.map(id => getSessionById(id)).filter(Boolean);
}

// Helper function to get bookmarkable sessions only
export function getBookmarkableSessions() {
  return sessions.filter(s => s.isBookmarkable);
}

// Type colors mapping
export const typeColors = {
  session: { bg: 'bg-brand-teal/5', text: 'text-brand-teal', border: 'border-brand-teal/20' },
  workshop: { bg: 'bg-brand-cardinal/5', text: 'text-brand-cardinal', border: 'border-brand-cardinal/20' },
  break: { bg: 'bg-brand-cream', text: 'text-brand-ink/60', border: 'border-brand-ink/10' },
  special: { bg: 'bg-brand-green-dark/5', text: 'text-brand-green-dark', border: 'border-brand-green-dark/20' },
  lightning: { bg: 'bg-brand-gold/10', text: 'text-brand-gold', border: 'border-brand-gold/20' },
};

// Generation metadata
export const metadata = {
  generatedAt: '2025-12-15T19:11:43.902Z',
  totalSessions: 4,
  mondaySessions: 4,
  tuesdaySessions: 0,
};

export default {
  sessions,
  sessionsByDay,
  sessionTypes,
  sessionTracks,
  getSessionById,
  getSessionsByIds,
  getBookmarkableSessions,
  typeColors,
  metadata
};
