/**
 * Schedule data generated from Airtable
 *
 * Generated: 2025-12-15T21:59:55.744Z
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * To update:
 * 1. Edit the "Schedule" table in Airtable
 * 2. Run: npm run generate-schedule
 * 3. Review changes and commit
 */

// All sessions (sorted by day, then order)
export const sessions = [];

// Sessions grouped by day
export const sessionsByDay = {
  "monday": [],
  "tuesday": []
};

// Available session types for filtering
export const sessionTypes = [];

// Available tracks for filtering
export const sessionTracks = [];

// Helper function to get a session by ID
export function getSessionById(id) {
  return sessions.find(s => s.id === id) || null;
}

// Helper function to get multiple sessions by IDs
export function getSessionsByIds(ids) {
  return ids.map(id => getSessionById(id)).filter(Boolean);
}

// Helper function to get bookmarkable sessions only
export function getBookmarkableSessions() {
  return sessions.filter(s => s.isBookmarkable);
}

// Type colors mapping
export const typeColors = {
  session: { bg: 'bg-brand-teal/5', text: 'text-brand-teal', border: 'border-brand-teal/20' },
  workshop: { bg: 'bg-brand-cardinal/5', text: 'text-brand-cardinal', border: 'border-brand-cardinal/20' },
  break: { bg: 'bg-brand-cream', text: 'text-brand-ink/60', border: 'border-brand-ink/10' },
  special: { bg: 'bg-brand-green-dark/5', text: 'text-brand-green-dark', border: 'border-brand-green-dark/20' },
  lightning: { bg: 'bg-brand-gold/10', text: 'text-brand-gold', border: 'border-brand-gold/20' },
};

// Generation metadata
export const metadata = {
  generatedAt: '2025-12-15T21:59:55.744Z',
  totalSessions: 0,
  mondaySessions: 0,
  tuesdaySessions: 0,
};

export default {
  sessions,
  sessionsByDay,
  sessionTypes,
  sessionTracks,
  getSessionById,
  getSessionsByIds,
  getBookmarkableSessions,
  typeColors,
  metadata
};
