/**
 * Site content generated from Airtable
 *
 * Generated: 2025-12-15T16:46:22.121Z
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * To update content:
 * 1. Edit the "Site Content" table in Airtable
 * 2. Run: npm run generate-content
 * 3. Review changes and commit
 */

// All content organized by section
export const sections = {
  "footer": {
    "twitter_handle": {
      "value": "@CenterCoopMedia",
      "color": "cream",
      "order": 94,
      "component": "Footer",
      "link": "",
      "page": "Global"
    },
    "inn_logo_alt": {
      "value": "Institute for Nonprofit News logo",
      "color": "cream",
      "order": 97,
      "component": "Footer",
      "link": "",
      "page": "Global"
    },
    "ccm_logo_alt": {
      "value": "Center for Cooperative Media logo",
      "color": "cream",
      "order": 96,
      "component": "Footer",
      "link": "",
      "page": "Global"
    },
    "contact_email": {
      "value": "summit@collaborativejournalism.org",
      "color": "cream",
      "order": 92,
      "component": "Footer",
      "link": "",
      "page": "Global"
    },
    "website_url": {
      "value": "collaborativejournalism.org",
      "color": "cream",
      "order": 93,
      "component": "Footer",
      "link": "",
      "page": "Global"
    },
    "signup_description": {
      "value": "Secure your spot at the 10th anniversary summit.",
      "color": "cream",
      "order": 91,
      "component": "Footer",
      "link": "",
      "page": "Global"
    },
    "signup_headline": {
      "value": "Join us in Chapel Hill",
      "color": "cream",
      "order": 90,
      "component": "Footer",
      "link": "",
      "page": "Global"
    },
    "copyright": {
      "value": "2026 Center for Cooperative Media at Montclair State University",
      "color": "cream",
      "order": 95,
      "component": "Footer",
      "link": "",
      "page": "Global"
    }
  },
  "schedule": {
    "monday_subtitle": {
      "value": "Main summit day",
      "color": "teal",
      "order": 105,
      "component": "DaySubtitle",
      "link": "",
      "page": "Schedule"
    },
    "tuesday_label": {
      "value": "Tuesday, June 9",
      "color": "cardinal",
      "order": 106,
      "component": "DayLabel",
      "link": "",
      "page": "Home"
    },
    "page_description": {
      "value": "Two days of sessions, workshops, and networking. Programming details will be announced in spring 2026.",
      "color": "ink",
      "order": 101,
      "component": "PageDescription",
      "link": "",
      "page": "Schedule"
    },
    "inn_days_description": {
      "value": "INN Days runs June 9-11 at the same venue. Attend both events in one trip.",
      "color": "green-dark",
      "order": 109,
      "component": "SectionDescription",
      "link": "",
      "page": "Schedule"
    },
    "monday_label": {
      "value": "Monday, June 8",
      "color": "teal",
      "order": 104,
      "component": "DayLabel",
      "link": "",
      "page": "Schedule"
    },
    "preliminary_notice": {
      "value": "Session pitches will be accepted through Jan. 31, 2026. Session topics and speakers will be announced in spring 2026. ",
      "color": "ink",
      "order": 103,
      "component": "Notice",
      "link": "",
      "page": "Home"
    },
    "page_headline": {
      "value": "Schedule",
      "color": "ink",
      "order": 100,
      "component": "PageHeadline",
      "link": "",
      "page": "Home"
    },
    "tuesday_subtitle": {
      "value": "Workshop day",
      "color": "cardinal",
      "order": 107,
      "component": "DaySubtitle",
      "link": "",
      "page": "Schedule"
    },
    "inn_days_title": {
      "value": "Co-located with INN Days",
      "color": "green-dark",
      "order": 108,
      "component": "SectionTitle",
      "link": "",
      "page": "Schedule"
    },
    "preliminary_label": {
      "value": "Preliminary schedule",
      "color": "teal",
      "order": 102,
      "component": "Badge",
      "link": "",
      "page": "Home"
    }
  },
  "login": {
    "email_label": {
      "value": "Email address",
      "color": "ink",
      "order": 191,
      "component": "FormLabel",
      "link": "",
      "page": "Login"
    },
    "page_headline": {
      "value": "Sign in",
      "color": "ink",
      "order": 190,
      "component": "PageHeadline",
      "link": "",
      "page": "Login"
    },
    "submit_button": {
      "value": "Create account",
      "color": "teal",
      "order": 193,
      "component": "Button",
      "link": "",
      "page": "Login"
    }
  },
  "details": {
    "when_day1_description": {
      "value": "Half-day of keynotes, sessions and an awards dinner",
      "color": "cardinal",
      "order": 10,
      "component": "DetailsCard",
      "link": "",
      "page": "Home"
    },
    "who_description": {
      "value": "Journalists, media leaders, funders, and academics",
      "color": "cardinal",
      "order": 17,
      "component": "DetailsCard",
      "link": "",
      "page": "Home"
    },
    "venue_note": {
      "value": "Co-located with INN Days",
      "color": "cardinal",
      "order": 15,
      "component": "DetailsCard",
      "link": "",
      "page": "Home"
    },
    "section_headline": {
      "value": "Save the date",
      "color": "ink",
      "order": 8,
      "component": "SectionHeadline",
      "link": "",
      "page": "Home"
    },
    "venue_name": {
      "value": "UNC Friday Center",
      "color": "cardinal",
      "order": 13,
      "component": "DetailsCard",
      "link": "",
      "page": "Home"
    },
    "when_day2_title": {
      "value": "Tuesday, June 9",
      "color": "cardinal",
      "order": 11,
      "component": "DetailsCard",
      "link": "",
      "page": "Home"
    },
    "location": {
      "value": "Chapel Hill, North Carolina",
      "color": "ink",
      "order": 5,
      "component": "HeroText",
      "link": "",
      "page": "Home"
    },
    "headline": {
      "value": "Collaborative Journalism Summit",
      "color": "ink",
      "order": 2,
      "component": "HeroHeadline",
      "link": "",
      "page": "Home"
    },
    "badge_text": {
      "value": "10th anniversary edition",
      "color": "gold",
      "order": 6,
      "component": "HeroBadge",
      "link": "",
      "page": "Home"
    },
    "venue_location": {
      "value": "Chapel Hill, North Carolina",
      "color": "cardinal",
      "order": 14,
      "component": "DetailsCard",
      "link": "",
      "page": "Home"
    },
    "tagline": {
      "value": "Prepare to partner.",
      "color": "cardinal",
      "order": 3,
      "component": "HeroTagline",
      "link": "",
      "page": "Home"
    },
    "who_count": {
      "value": "130-150 attendees",
      "color": "cardinal",
      "order": 16,
      "component": "DetailsCard",
      "link": "",
      "page": "Home"
    },
    "when_day2_description": {
      "value": "Full day of sessions, workshops and lightning talks",
      "color": "cardinal",
      "order": 12,
      "component": "DetailsCard",
      "link": "",
      "page": "Home"
    },
    "registration_note": {
      "value": "Tickets now available",
      "color": "ink",
      "order": 7,
      "component": "HeroNote",
      "link": "",
      "page": "Home"
    },
    "date_display": {
      "value": "June 8–9, 2026",
      "color": "ink",
      "order": 4,
      "component": "HeroText",
      "link": "",
      "page": "Home"
    },
    "when_day1_title": {
      "value": "Monday, June 8",
      "color": "ink",
      "order": 9,
      "component": "DetailsCard",
      "link": "",
      "page": "Home"
    },
    "section_description": {
      "value": "Since 2017, the Collaborative Journalism Summit has brought together practitioners, funders, and innovators. This year, we celebrate a decade of proving that journalism is stronger when we collaborate.",
      "color": "ink",
      "order": 9,
      "component": "SectionDescription",
      "link": "",
      "page": "Home"
    },
    "year": {
      "value": "2026",
      "color": "teal",
      "order": 1,
      "component": "HeroYear",
      "link": "",
      "page": "Home"
    }
  },
  "contact": {
    "twitter_description": {
      "value": "Follow us for summit updates and collaborative journalism news",
      "color": "ink",
      "order": 167,
      "component": "ContactCard",
      "link": "",
      "page": "Home"
    },
    "organizer_headline": {
      "value": "About the organizers",
      "color": "ink",
      "order": 168,
      "component": "SectionHeadline",
      "link": "",
      "page": "Home"
    },
    "inn_description": {
      "value": "A network of more than 450 nonprofit news organizations. INN supports, connects, and champions public service journalism.",
      "color": "cardinal",
      "order": 173,
      "component": "OrganizerCard",
      "link": "",
      "page": "Contact"
    },
    "twitter_label": {
      "value": "Twitter/X",
      "color": "ink",
      "order": 165,
      "component": "ContactCard",
      "link": "",
      "page": "Home"
    },
    "email_description": {
      "value": "For general inquiries, sponsorship questions, and press requests",
      "color": "teal",
      "order": 164,
      "component": "ContactCard",
      "link": "",
      "page": "Contact"
    },
    "inn_name": {
      "value": "Institute for Nonprofit News",
      "color": "cardinal",
      "order": 172,
      "component": "OrganizerCard",
      "link": "",
      "page": "Contact"
    },
    "email_value": {
      "value": "summit@collaborativejournalism.org",
      "color": "teal",
      "order": 163,
      "component": "ContactCard",
      "link": "",
      "page": "Contact"
    },
    "email_label": {
      "value": "Email address",
      "color": "ink",
      "order": 162,
      "component": "ContactCard",
      "link": "",
      "page": "Contact"
    },
    "ccm_description": {
      "value": "A grant-funded program of the School of Communication and Media at Montclair State University. The Center grows and strengthens local journalism in New Jersey and beyond.",
      "color": "teal",
      "order": 170,
      "component": "OrganizerCard",
      "link": "",
      "page": "Contact"
    },
    "page_headline": {
      "value": "Contact us",
      "color": "ink",
      "order": 160,
      "component": "PageHeadline",
      "link": "",
      "page": "Contact"
    },
    "ccm_name": {
      "value": "Center for Cooperative Media",
      "color": "teal",
      "order": 169,
      "component": "OrganizerCard",
      "link": "",
      "page": "Home"
    },
    "ccm_url": {
      "value": "https://centerforcooperativemedia.org",
      "color": "teal",
      "order": 171,
      "component": "OrganizerCard",
      "link": "",
      "page": "Contact"
    },
    "twitter_value": {
      "value": "@CenterCoopMedia",
      "color": "ink",
      "order": 166,
      "component": "ContactCard",
      "link": "",
      "page": "Contact"
    },
    "page_description": {
      "value": "Have questions about the Collaborative Journalism Summit? We're here to help.",
      "color": "ink",
      "order": 161,
      "component": "PageDescription",
      "link": "",
      "page": "Home"
    },
    "inn_url": {
      "value": "https://inn.org",
      "color": "cardinal",
      "order": 174,
      "component": "OrganizerCard",
      "link": "",
      "page": "Contact"
    }
  },
  "stats": {
    "mission_label": {
      "value": "Mission",
      "color": "teal",
      "order": 37,
      "component": "StatCard",
      "link": "",
      "page": "Home"
    },
    "mission_value": {
      "value": "1",
      "color": "teal",
      "order": 36,
      "component": "StatCard",
      "link": "",
      "page": "Home"
    },
    "attendees_label": {
      "value": "Attendees",
      "color": "teal",
      "order": 35,
      "component": "StatCard",
      "link": "",
      "page": "Home"
    },
    "cities_value": {
      "value": "7",
      "color": "teal",
      "order": 32,
      "component": "StatCard",
      "link": "",
      "page": "Home"
    },
    "summits_value": {
      "value": "10",
      "color": "teal",
      "order": 30,
      "component": "StatCard",
      "link": "",
      "page": "Home"
    },
    "cities_label": {
      "value": "Cities",
      "color": "teal",
      "order": 33,
      "component": "StatCard",
      "link": "",
      "page": "Home"
    },
    "summits_label": {
      "value": "Summits",
      "color": "teal",
      "order": 31,
      "component": "StatCard",
      "link": "",
      "page": "Home"
    },
    "attendees_value": {
      "value": "1500+",
      "color": "teal",
      "order": 34,
      "component": "StatCard",
      "link": "",
      "page": "Home"
    }
  },
  "register": {
    "email_label": {
      "value": "Email address",
      "color": "ink",
      "order": 202,
      "component": "FormLabel",
      "link": "",
      "page": "Register"
    },
    "login_prompt": {
      "value": "Already have an account?",
      "color": "ink",
      "order": 206,
      "component": "Text",
      "link": "",
      "page": "Register"
    },
    "submit_button": {
      "value": "Create account",
      "color": "teal",
      "order": 205,
      "component": "Button",
      "link": "",
      "page": "Register"
    }
  },
  "navbar": {
    "brand_text": {
      "value": "CJS 2026",
      "color": "ink",
      "order": 180,
      "component": "Navbar",
      "link": "",
      "page": "Global"
    },
    "home_link": {
      "value": "Home",
      "color": "ink",
      "order": 181,
      "component": "NavLink",
      "link": "",
      "page": "Global"
    },
    "contact_link": {
      "value": "Contact",
      "color": "ink",
      "order": 184,
      "component": "NavLink",
      "link": "",
      "page": "Global"
    },
    "sponsors_link": {
      "value": "Sponsors",
      "color": "ink",
      "order": 183,
      "component": "NavLink",
      "link": "",
      "page": "Global"
    },
    "code_of_conduct_link": {
      "value": "Code of conduct",
      "color": "ink",
      "order": 185,
      "component": "NavLink",
      "link": "",
      "page": "Global"
    },
    "schedule_link": {
      "value": "Schedule",
      "color": "ink",
      "order": 182,
      "component": "NavLink",
      "link": "",
      "page": "Global"
    }
  },
  "code_of_conduct": {
    "consequences_text": {
      "value": "Anyone asked to stop unacceptable behavior is expected to comply immediately. If a participant engages in unacceptable behavior, the conference organizers may take any action they deem appropriate, up to and including a temporary ban or permanent expulsion from the event without warning or refund.",
      "color": "ink",
      "order": 150,
      "component": "BodyText",
      "link": "",
      "page": "Code of Conduct"
    },
    "page_headline": {
      "value": "Code of conduct",
      "color": "ink",
      "order": 140,
      "component": "PageHeadline",
      "link": "",
      "page": "Code of Conduct"
    },
    "intro": {
      "value": "We are committed to creating a welcoming and inclusive environment for all participants, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, or technology choices.",
      "color": "ink",
      "order": 142,
      "component": "IntroText",
      "link": "",
      "page": "Code of Conduct"
    },
    "reporting_text": {
      "value": "If you experience or witness unacceptable behavior, or have any other concerns, please notify a conference organizer as soon as possible. You can reach us at summit@collaborativejournalism.org or speak with any staff member at the registration desk.",
      "color": "ink",
      "order": 148,
      "component": "BodyText",
      "link": "",
      "page": "Code of Conduct"
    },
    "unacceptable_items": {
      "value": "Intimidating, harassing, abusive, discriminatory, derogatory, or demeaning speech or actions\nHarmful or prejudicial verbal or written comments related to gender, gender identity, sexual orientation, race, religion, disability\nInappropriate use of nudity and/or sexual images\nDeliberate intimidation, stalking, or following\nSustained disruption of talks or other events\nUnwelcome physical contact or sexual attention\nAdvocating for or encouraging any of the above behaviors",
      "color": "cardinal",
      "order": 146,
      "component": "List",
      "link": "",
      "page": "Code of Conduct"
    },
    "expected_headline": {
      "value": "Expected behavior",
      "color": "teal",
      "order": 143,
      "component": "SectionHeadline",
      "link": "",
      "page": "Code of Conduct"
    },
    "consequences_headline": {
      "value": "Consequences",
      "color": "ink",
      "order": 149,
      "component": "SectionHeadline",
      "link": "",
      "page": "Home"
    },
    "reporting_headline": {
      "value": "Reporting",
      "color": "ink",
      "order": 147,
      "component": "SectionHeadline",
      "link": "",
      "page": "Home"
    },
    "unacceptable_headline": {
      "value": "Unacceptable behavior",
      "color": "cardinal",
      "order": 145,
      "component": "SectionHeadline",
      "link": "",
      "page": "Code of Conduct"
    },
    "page_description": {
      "value": "Have questions about the Collaborative Journalism Summit? We're here to help.",
      "color": "ink",
      "order": 141,
      "component": "PageDescription",
      "link": "",
      "page": "Code of Conduct"
    },
    "expected_items": {
      "value": "Participate authentically and actively\nExercise consideration and respect in your speech and actions\nAttempt collaboration before conflict\nRefrain from demeaning, discriminatory, or harassing behavior and speech\nBe mindful of your surroundings and fellow participants\nAlert conference organizers if you notice violations or someone in distress",
      "color": "teal",
      "order": 144,
      "component": "List",
      "link": "",
      "page": "Home"
    }
  },
  "timeline": {
    "2024_location": {
      "value": "Detroit, MI",
      "color": "cardinal",
      "order": 69,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2023_location": {
      "value": "Washington, D.C.",
      "color": "teal",
      "order": 65,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2023_link": {
      "value": "https://collaborativejournalism.org/cjs2023/",
      "color": "teal",
      "order": 67,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2017_link": {
      "value": "https://www.montclair.edu/college-of-communication-and-media/2017/06/07/18156_collaborative-journalism-summit-highlights-new-ideas-for-impactful-reporting/",
      "color": "teal",
      "order": 43,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2017_theme": {
      "value": "The Beginning",
      "color": "teal",
      "order": 42,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2022_link": {
      "value": "https://collaborativejournalism.org/cjs2022/",
      "color": "green-dark",
      "order": 63,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2017_year": {
      "value": "2017",
      "color": "teal",
      "order": 40,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2022_theme": {
      "value": "Building to Last",
      "color": "green-dark",
      "order": 62,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2018_theme": {
      "value": "Building Bridges",
      "color": "teal",
      "order": 46,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2024_year": {
      "value": "2024",
      "color": "cardinal",
      "order": 68,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2022_location": {
      "value": "Chicago, IL",
      "color": "green-dark",
      "order": 61,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2021_link": {
      "value": "https://collaborativejournalism.org/cjs2021/",
      "color": "ink",
      "order": 59,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2024_link": {
      "value": "https://collaborativejournalism.org/cjs2024/",
      "color": "cardinal",
      "order": 71,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2021_location": {
      "value": "Virtual",
      "color": "ink",
      "order": 57,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2025_link": {
      "value": "https://collaborativejournalism.org/cjs2025/",
      "color": "green-dark",
      "order": 75,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2020_link": {
      "value": "https://collaborativejournalism.org/cjs2020/",
      "color": "ink",
      "order": 55,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2023_year": {
      "value": "2023",
      "color": "teal",
      "order": 64,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2020_theme": {
      "value": "Adapting Together",
      "color": "ink",
      "order": 54,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2018_location": {
      "value": "Montclair, NJ",
      "color": "teal",
      "order": 45,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2019_link": {
      "value": "https://collaborativejournalism.org/cjs2019/",
      "color": "cardinal",
      "order": 51,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2026_theme": {
      "value": "10th Anniversary",
      "color": "gold",
      "order": 78,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2023_theme": {
      "value": "Building Frameworks",
      "color": "teal",
      "order": 66,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2020_location": {
      "value": "Virtual",
      "color": "ink",
      "order": 53,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2026_location": {
      "value": "Chapel Hill, NC",
      "color": "gold",
      "order": 77,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2019_theme": {
      "value": "People Over Projects",
      "color": "cardinal",
      "order": 50,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2020_year": {
      "value": "2020",
      "color": "ink",
      "order": 52,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2019_year": {
      "value": "2019",
      "color": "cardinal",
      "order": 48,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2017_location": {
      "value": "Montclair, NJ",
      "color": "teal",
      "order": 41,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2025_location": {
      "value": "Denver, CO",
      "color": "green-dark",
      "order": 73,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2018_year": {
      "value": "2018",
      "color": "teal",
      "order": 44,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2019_location": {
      "value": "Philadelphia, PA",
      "color": "cardinal",
      "order": 49,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2026_year": {
      "value": "2026",
      "color": "gold",
      "order": 76,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2021_year": {
      "value": "2021",
      "color": "ink",
      "order": 56,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2025_theme": {
      "value": "Partnerships with Purpose",
      "color": "green-dark",
      "order": 74,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2021_theme": {
      "value": "Removing Barriers",
      "color": "ink",
      "order": 58,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2018_link": {
      "value": "https://collaborativejournalism.org/2018summit/",
      "color": "teal",
      "order": 47,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2025_year": {
      "value": "2025",
      "color": "green-dark",
      "order": 72,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2022_year": {
      "value": "2022",
      "color": "green-dark",
      "order": 60,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    },
    "2024_theme": {
      "value": "Global Impact",
      "color": "cardinal",
      "order": 70,
      "component": "TimelineCard",
      "link": "",
      "page": "Home"
    }
  },
  "sponsors": {
    "audience_title": {
      "value": "Engaged audience",
      "color": "teal",
      "order": 127,
      "component": "BenefitCard",
      "link": "",
      "page": "Home"
    },
    "open_description": {
      "value": "Be among the first to support the 10th anniversary summit. Sponsors will be recognized here as they are confirmed.",
      "color": "ink",
      "order": 123,
      "component": "Notice",
      "link": "",
      "page": "Sponsors"
    },
    "custom_description": {
      "value": "Interested in sponsoring a specific element of the summit? We offer custom packages for:",
      "color": "ink",
      "order": 134,
      "component": "SectionDescription",
      "link": "",
      "page": "Sponsors"
    },
    "milestone_description": {
      "value": "Be part of our 10th anniversary celebration - a landmark moment in the collaborative journalism movement.",
      "color": "teal",
      "order": 126,
      "component": "BenefitCard",
      "link": "",
      "page": "Home"
    },
    "audience_description": {
      "value": "Connect with journalists, editors, funders, and media leaders actively working on collaborative projects.",
      "color": "teal",
      "order": 128,
      "component": "BenefitCard",
      "link": "",
      "page": "Home"
    },
    "cta_headline": {
      "value": "Ready to sponsor?",
      "color": "cardinal",
      "order": 131,
      "component": "SectionHeadline",
      "link": "",
      "page": "Sponsors"
    },
    "custom_headline": {
      "value": "Custom sponsorship opportunities",
      "color": "ink",
      "order": 133,
      "component": "SectionHeadline",
      "link": "",
      "page": "Sponsors"
    },
    "cta_description": {
      "value": "Contact us to discuss sponsorship opportunities and receive a full prospectus.",
      "color": "cardinal",
      "order": 132,
      "component": "SectionDescription",
      "link": "",
      "page": "Home"
    },
    "exposure_description": {
      "value": "Co-located with INN Days means additional visibility to the nonprofit news community.",
      "color": "teal",
      "order": 130,
      "component": "BenefitCard",
      "link": "",
      "page": "Sponsors"
    },
    "page_description": {
      "value": "Support the 10th anniversary Collaborative Journalism Summit and connect with 130+ leaders in collaborative journalism.",
      "color": "ink",
      "order": 121,
      "component": "PageDescription",
      "link": "",
      "page": "Home"
    },
    "exposure_title": {
      "value": "Dual-event exposure",
      "color": "teal",
      "order": 129,
      "component": "BenefitCard",
      "link": "",
      "page": "Sponsors"
    },
    "page_headline": {
      "value": "Dashboard",
      "color": "ink",
      "order": 120,
      "component": "PageHeadline",
      "link": "",
      "page": "Sponsors"
    },
    "milestone_title": {
      "value": "Milestone event",
      "color": "teal",
      "order": 125,
      "component": "BenefitCard",
      "link": "",
      "page": "Home"
    },
    "why_sponsor_headline": {
      "value": "Why sponsor the summit?",
      "color": "ink",
      "order": 124,
      "component": "SectionHeadline",
      "link": "",
      "page": "Sponsors"
    },
    "open_label": {
      "value": "Sponsorships now open",
      "color": "teal",
      "order": 122,
      "component": "Badge",
      "link": "",
      "page": "Sponsors"
    }
  },
  "expect": {
    "monday_items": {
      "value": "8 curated sessions with invited speakers\n8 lightning talks from community pitches\nNetworking opportunities throughout\nEvening dinner and celebration",
      "color": "teal",
      "order": 82,
      "component": "ExpectCard",
      "link": "",
      "page": "Home"
    },
    "monday_label": {
      "value": "Monday: Main summit",
      "color": "teal",
      "order": 81,
      "component": "ExpectCard",
      "link": "",
      "page": "Home"
    },
    "tuesday_label": {
      "value": "Tuesday: Workshops",
      "color": "cardinal",
      "order": 83,
      "component": "ExpectCard",
      "link": "",
      "page": "Home"
    },
    "section_headline": {
      "value": "What to expect",
      "color": "ink",
      "order": 80,
      "component": "SectionHeadline",
      "link": "",
      "page": "Home"
    },
    "tuesday_items": {
      "value": "Track 1: Collaborating 101\nTrack 2: Advanced collaboration\nHands-on learning and skill building",
      "color": "cardinal",
      "order": 84,
      "component": "ExpectCard",
      "link": "",
      "page": "Home"
    }
  },
  "history": {
    "section_description": {
      "value": "Since 2017, the Collaborative Journalism Summit has brought together practitioners, funders, and innovators. This year, we celebrate a decade of proving that journalism is stronger when we collaborate.",
      "color": "ink",
      "order": 21,
      "component": "SectionDescription",
      "link": "",
      "page": "Home"
    },
    "section_headline": {
      "value": "What to expect",
      "color": "ink",
      "order": 20,
      "component": "SectionHeadline",
      "link": "",
      "page": "Home"
    }
  },
  "dashboard": {
    "signout_button": {
      "value": "Sign out",
      "color": "cardinal",
      "order": 212,
      "component": "Button",
      "link": "",
      "page": "Dashboard"
    },
    "welcome_message": {
      "value": "Welcome back!",
      "color": "ink",
      "order": 211,
      "component": "WelcomeText",
      "link": "",
      "page": "Dashboard"
    },
    "page_headline": {
      "value": "Dashboard",
      "color": "ink",
      "order": 210,
      "component": "PageHeadline",
      "link": "",
      "page": "Dashboard"
    }
  }
};

// Content organized by page
export const byPage = {
  "Global": {
    "footer": {
      "twitter_handle": {
        "value": "@CenterCoopMedia",
        "color": "cream",
        "order": 94,
        "component": "Footer",
        "link": ""
      },
      "inn_logo_alt": {
        "value": "Institute for Nonprofit News logo",
        "color": "cream",
        "order": 97,
        "component": "Footer",
        "link": ""
      },
      "ccm_logo_alt": {
        "value": "Center for Cooperative Media logo",
        "color": "cream",
        "order": 96,
        "component": "Footer",
        "link": ""
      },
      "contact_email": {
        "value": "summit@collaborativejournalism.org",
        "color": "cream",
        "order": 92,
        "component": "Footer",
        "link": ""
      },
      "website_url": {
        "value": "collaborativejournalism.org",
        "color": "cream",
        "order": 93,
        "component": "Footer",
        "link": ""
      },
      "signup_description": {
        "value": "Secure your spot at the 10th anniversary summit.",
        "color": "cream",
        "order": 91,
        "component": "Footer",
        "link": ""
      },
      "signup_headline": {
        "value": "Join us in Chapel Hill",
        "color": "cream",
        "order": 90,
        "component": "Footer",
        "link": ""
      },
      "copyright": {
        "value": "2026 Center for Cooperative Media at Montclair State University",
        "color": "cream",
        "order": 95,
        "component": "Footer",
        "link": ""
      }
    },
    "navbar": {
      "brand_text": {
        "value": "CJS 2026",
        "color": "ink",
        "order": 180,
        "component": "Navbar",
        "link": ""
      },
      "home_link": {
        "value": "Home",
        "color": "ink",
        "order": 181,
        "component": "NavLink",
        "link": ""
      },
      "contact_link": {
        "value": "Contact",
        "color": "ink",
        "order": 184,
        "component": "NavLink",
        "link": ""
      },
      "sponsors_link": {
        "value": "Sponsors",
        "color": "ink",
        "order": 183,
        "component": "NavLink",
        "link": ""
      },
      "code_of_conduct_link": {
        "value": "Code of conduct",
        "color": "ink",
        "order": 185,
        "component": "NavLink",
        "link": ""
      },
      "schedule_link": {
        "value": "Schedule",
        "color": "ink",
        "order": 182,
        "component": "NavLink",
        "link": ""
      }
    }
  },
  "Schedule": {
    "schedule": {
      "monday_subtitle": {
        "value": "Main summit day",
        "color": "teal",
        "order": 105,
        "component": "DaySubtitle",
        "link": ""
      },
      "tuesday_label": {
        "value": "Tuesday, June 9",
        "color": "cardinal",
        "order": 106,
        "component": "DayLabel",
        "link": ""
      },
      "page_description": {
        "value": "Two days of sessions, workshops, and networking. Programming details will be announced in spring 2026.",
        "color": "ink",
        "order": 101,
        "component": "PageDescription",
        "link": ""
      },
      "inn_days_description": {
        "value": "INN Days runs June 9-11 at the same venue. Attend both events in one trip.",
        "color": "green-dark",
        "order": 109,
        "component": "SectionDescription",
        "link": ""
      },
      "monday_label": {
        "value": "Monday, June 8",
        "color": "teal",
        "order": 104,
        "component": "DayLabel",
        "link": ""
      },
      "preliminary_notice": {
        "value": "Session topics and speakers will be announced in spring 2026. Sign up for updates to be the first to know.",
        "color": "ink",
        "order": 103,
        "component": "Notice",
        "link": ""
      },
      "page_headline": {
        "value": "Schedule",
        "color": "ink",
        "order": 100,
        "component": "PageHeadline",
        "link": ""
      },
      "tuesday_subtitle": {
        "value": "Workshop day",
        "color": "cardinal",
        "order": 107,
        "component": "DaySubtitle",
        "link": ""
      },
      "preliminary_label": {
        "value": "Preliminary schedule",
        "color": "teal",
        "order": 102,
        "component": "Badge",
        "link": ""
      },
      "inn_days_title": {
        "value": "Co-located with INN Days",
        "color": "green-dark",
        "order": 108,
        "component": "SectionTitle",
        "link": ""
      }
    }
  },
  "Login": {
    "login": {
      "email_label": {
        "value": "Email address",
        "color": "ink",
        "order": 191,
        "component": "FormLabel",
        "link": ""
      },
      "page_headline": {
        "value": "Sign in",
        "color": "ink",
        "order": 190,
        "component": "PageHeadline",
        "link": ""
      },
      "submit_button": {
        "value": "Create account",
        "color": "teal",
        "order": 193,
        "component": "Button",
        "link": ""
      }
    }
  },
  "Home": {
    "details": {
      "when_day1_description": {
        "value": "Half-day of keynotes, sessions and an awards dinner",
        "color": "cardinal",
        "order": 10,
        "component": "DetailsCard",
        "link": ""
      },
      "who_description": {
        "value": "Journalists, media leaders, funders, and academics",
        "color": "cardinal",
        "order": 17,
        "component": "DetailsCard",
        "link": ""
      },
      "venue_note": {
        "value": "Co-located with INN Days",
        "color": "cardinal",
        "order": 15,
        "component": "DetailsCard",
        "link": ""
      },
      "section_headline": {
        "value": "Save the date",
        "color": "ink",
        "order": 8,
        "component": "SectionHeadline",
        "link": ""
      },
      "venue_name": {
        "value": "UNC Friday Center",
        "color": "cardinal",
        "order": 13,
        "component": "DetailsCard",
        "link": ""
      },
      "when_day2_title": {
        "value": "Tuesday, June 9",
        "color": "cardinal",
        "order": 11,
        "component": "DetailsCard",
        "link": ""
      },
      "location": {
        "value": "Chapel Hill, North Carolina",
        "color": "ink",
        "order": 5,
        "component": "HeroText",
        "link": ""
      },
      "headline": {
        "value": "Collaborative Journalism Summit",
        "color": "ink",
        "order": 2,
        "component": "HeroHeadline",
        "link": ""
      },
      "badge_text": {
        "value": "10th anniversary edition",
        "color": "gold",
        "order": 6,
        "component": "HeroBadge",
        "link": ""
      },
      "venue_location": {
        "value": "Chapel Hill, North Carolina",
        "color": "cardinal",
        "order": 14,
        "component": "DetailsCard",
        "link": ""
      },
      "tagline": {
        "value": "Prepare to partner.",
        "color": "cardinal",
        "order": 3,
        "component": "HeroTagline",
        "link": ""
      },
      "who_count": {
        "value": "130-150 attendees",
        "color": "cardinal",
        "order": 16,
        "component": "DetailsCard",
        "link": ""
      },
      "when_day2_description": {
        "value": "Full day of sessions, workshops and lightning talks",
        "color": "cardinal",
        "order": 12,
        "component": "DetailsCard",
        "link": ""
      },
      "registration_note": {
        "value": "Tickets now available",
        "color": "ink",
        "order": 7,
        "component": "HeroNote",
        "link": ""
      },
      "date_display": {
        "value": "June 8–9, 2026",
        "color": "ink",
        "order": 4,
        "component": "HeroText",
        "link": ""
      },
      "when_day1_title": {
        "value": "Monday, June 8",
        "color": "ink",
        "order": 9,
        "component": "DetailsCard",
        "link": ""
      },
      "section_description": {
        "value": "Since 2017, the Collaborative Journalism Summit has brought together practitioners, funders, and innovators. This year, we celebrate a decade of proving that journalism is stronger when we collaborate.",
        "color": "ink",
        "order": 9,
        "component": "SectionDescription",
        "link": ""
      },
      "year": {
        "value": "2026",
        "color": "teal",
        "order": 1,
        "component": "HeroYear",
        "link": ""
      }
    },
    "stats": {
      "mission_label": {
        "value": "Mission",
        "color": "teal",
        "order": 37,
        "component": "StatCard",
        "link": ""
      },
      "mission_value": {
        "value": "1",
        "color": "teal",
        "order": 36,
        "component": "StatCard",
        "link": ""
      },
      "attendees_label": {
        "value": "Attendees",
        "color": "teal",
        "order": 35,
        "component": "StatCard",
        "link": ""
      },
      "cities_value": {
        "value": "7",
        "color": "teal",
        "order": 32,
        "component": "StatCard",
        "link": ""
      },
      "summits_value": {
        "value": "10",
        "color": "teal",
        "order": 30,
        "component": "StatCard",
        "link": ""
      },
      "cities_label": {
        "value": "Cities",
        "color": "teal",
        "order": 33,
        "component": "StatCard",
        "link": ""
      },
      "summits_label": {
        "value": "Summits",
        "color": "teal",
        "order": 31,
        "component": "StatCard",
        "link": ""
      },
      "attendees_value": {
        "value": "1500+",
        "color": "teal",
        "order": 34,
        "component": "StatCard",
        "link": ""
      }
    },
    "timeline": {
      "2024_location": {
        "value": "Detroit, MI",
        "color": "cardinal",
        "order": 69,
        "component": "TimelineCard",
        "link": ""
      },
      "2023_location": {
        "value": "Washington, D.C.",
        "color": "teal",
        "order": 65,
        "component": "TimelineCard",
        "link": ""
      },
      "2023_link": {
        "value": "https://collaborativejournalism.org/cjs2023/",
        "color": "teal",
        "order": 67,
        "component": "TimelineCard",
        "link": ""
      },
      "2017_link": {
        "value": "https://www.montclair.edu/college-of-communication-and-media/2017/06/07/18156_collaborative-journalism-summit-highlights-new-ideas-for-impactful-reporting/",
        "color": "teal",
        "order": 43,
        "component": "TimelineCard",
        "link": ""
      },
      "2017_theme": {
        "value": "The Beginning",
        "color": "teal",
        "order": 42,
        "component": "TimelineCard",
        "link": ""
      },
      "2022_link": {
        "value": "https://collaborativejournalism.org/cjs2022/",
        "color": "green-dark",
        "order": 63,
        "component": "TimelineCard",
        "link": ""
      },
      "2017_year": {
        "value": "2017",
        "color": "teal",
        "order": 40,
        "component": "TimelineCard",
        "link": ""
      },
      "2022_theme": {
        "value": "Building to Last",
        "color": "green-dark",
        "order": 62,
        "component": "TimelineCard",
        "link": ""
      },
      "2018_theme": {
        "value": "Building Bridges",
        "color": "teal",
        "order": 46,
        "component": "TimelineCard",
        "link": ""
      },
      "2024_year": {
        "value": "2024",
        "color": "cardinal",
        "order": 68,
        "component": "TimelineCard",
        "link": ""
      },
      "2022_location": {
        "value": "Chicago, IL",
        "color": "green-dark",
        "order": 61,
        "component": "TimelineCard",
        "link": ""
      },
      "2021_link": {
        "value": "https://collaborativejournalism.org/cjs2021/",
        "color": "ink",
        "order": 59,
        "component": "TimelineCard",
        "link": ""
      },
      "2024_link": {
        "value": "https://collaborativejournalism.org/cjs2024/",
        "color": "cardinal",
        "order": 71,
        "component": "TimelineCard",
        "link": ""
      },
      "2021_location": {
        "value": "Virtual",
        "color": "ink",
        "order": 57,
        "component": "TimelineCard",
        "link": ""
      },
      "2025_link": {
        "value": "https://collaborativejournalism.org/cjs2025/",
        "color": "green-dark",
        "order": 75,
        "component": "TimelineCard",
        "link": ""
      },
      "2020_link": {
        "value": "https://collaborativejournalism.org/cjs2020/",
        "color": "ink",
        "order": 55,
        "component": "TimelineCard",
        "link": ""
      },
      "2023_year": {
        "value": "2023",
        "color": "teal",
        "order": 64,
        "component": "TimelineCard",
        "link": ""
      },
      "2020_theme": {
        "value": "Adapting Together",
        "color": "ink",
        "order": 54,
        "component": "TimelineCard",
        "link": ""
      },
      "2018_location": {
        "value": "Montclair, NJ",
        "color": "teal",
        "order": 45,
        "component": "TimelineCard",
        "link": ""
      },
      "2019_link": {
        "value": "https://collaborativejournalism.org/cjs2019/",
        "color": "cardinal",
        "order": 51,
        "component": "TimelineCard",
        "link": ""
      },
      "2026_theme": {
        "value": "10th Anniversary",
        "color": "gold",
        "order": 78,
        "component": "TimelineCard",
        "link": ""
      },
      "2023_theme": {
        "value": "Building Frameworks",
        "color": "teal",
        "order": 66,
        "component": "TimelineCard",
        "link": ""
      },
      "2020_location": {
        "value": "Virtual",
        "color": "ink",
        "order": 53,
        "component": "TimelineCard",
        "link": ""
      },
      "2026_location": {
        "value": "Chapel Hill, NC",
        "color": "gold",
        "order": 77,
        "component": "TimelineCard",
        "link": ""
      },
      "2019_theme": {
        "value": "People Over Projects",
        "color": "cardinal",
        "order": 50,
        "component": "TimelineCard",
        "link": ""
      },
      "2020_year": {
        "value": "2020",
        "color": "ink",
        "order": 52,
        "component": "TimelineCard",
        "link": ""
      },
      "2019_year": {
        "value": "2019",
        "color": "cardinal",
        "order": 48,
        "component": "TimelineCard",
        "link": ""
      },
      "2017_location": {
        "value": "Montclair, NJ",
        "color": "teal",
        "order": 41,
        "component": "TimelineCard",
        "link": ""
      },
      "2025_location": {
        "value": "Denver, CO",
        "color": "green-dark",
        "order": 73,
        "component": "TimelineCard",
        "link": ""
      },
      "2018_year": {
        "value": "2018",
        "color": "teal",
        "order": 44,
        "component": "TimelineCard",
        "link": ""
      },
      "2019_location": {
        "value": "Philadelphia, PA",
        "color": "cardinal",
        "order": 49,
        "component": "TimelineCard",
        "link": ""
      },
      "2026_year": {
        "value": "2026",
        "color": "gold",
        "order": 76,
        "component": "TimelineCard",
        "link": ""
      },
      "2021_year": {
        "value": "2021",
        "color": "ink",
        "order": 56,
        "component": "TimelineCard",
        "link": ""
      },
      "2025_theme": {
        "value": "Partnerships with Purpose",
        "color": "green-dark",
        "order": 74,
        "component": "TimelineCard",
        "link": ""
      },
      "2021_theme": {
        "value": "Removing Barriers",
        "color": "ink",
        "order": 58,
        "component": "TimelineCard",
        "link": ""
      },
      "2018_link": {
        "value": "https://collaborativejournalism.org/2018summit/",
        "color": "teal",
        "order": 47,
        "component": "TimelineCard",
        "link": ""
      },
      "2025_year": {
        "value": "2025",
        "color": "green-dark",
        "order": 72,
        "component": "TimelineCard",
        "link": ""
      },
      "2022_year": {
        "value": "2022",
        "color": "green-dark",
        "order": 60,
        "component": "TimelineCard",
        "link": ""
      },
      "2024_theme": {
        "value": "Global Impact",
        "color": "cardinal",
        "order": 70,
        "component": "TimelineCard",
        "link": ""
      }
    },
    "expect": {
      "monday_items": {
        "value": "8 curated sessions with invited speakers\n8 lightning talks from community pitches\nNetworking opportunities throughout\nEvening dinner and celebration",
        "color": "teal",
        "order": 82,
        "component": "ExpectCard",
        "link": ""
      },
      "monday_label": {
        "value": "Monday: Main summit",
        "color": "teal",
        "order": 81,
        "component": "ExpectCard",
        "link": ""
      },
      "tuesday_label": {
        "value": "Tuesday: Workshops",
        "color": "cardinal",
        "order": 83,
        "component": "ExpectCard",
        "link": ""
      },
      "section_headline": {
        "value": "What to expect",
        "color": "ink",
        "order": 80,
        "component": "SectionHeadline",
        "link": ""
      },
      "tuesday_items": {
        "value": "Track 1: Collaborating 101\nTrack 2: Advanced collaboration\nHands-on learning and skill building",
        "color": "cardinal",
        "order": 84,
        "component": "ExpectCard",
        "link": ""
      }
    },
    "history": {
      "section_description": {
        "value": "Since 2017, the Collaborative Journalism Summit has brought together practitioners, funders, and innovators. This year, we celebrate a decade of proving that journalism is stronger when we collaborate.",
        "color": "ink",
        "order": 21,
        "component": "SectionDescription",
        "link": ""
      },
      "section_headline": {
        "value": "What to expect",
        "color": "ink",
        "order": 20,
        "component": "SectionHeadline",
        "link": ""
      }
    },
    "sponsors": {
      "audience_title": {
        "value": "Engaged audience",
        "color": "teal",
        "order": 127,
        "component": "BenefitCard",
        "link": ""
      },
      "milestone_description": {
        "value": "Be part of our 10th anniversary celebration - a landmark moment in the collaborative journalism movement.",
        "color": "teal",
        "order": 126,
        "component": "BenefitCard",
        "link": ""
      },
      "exposure_title": {
        "value": "Dual-event exposure",
        "color": "teal",
        "order": 129,
        "component": "BenefitCard",
        "link": ""
      },
      "page_headline": {
        "value": "Sponsors",
        "color": "ink",
        "order": 120,
        "component": "PageHeadline",
        "link": ""
      },
      "why_sponsor_headline": {
        "value": "Why sponsor the summit?",
        "color": "ink",
        "order": 124,
        "component": "SectionHeadline",
        "link": ""
      },
      "open_label": {
        "value": "Sponsorships now open",
        "color": "teal",
        "order": 122,
        "component": "Badge",
        "link": ""
      },
      "audience_description": {
        "value": "Connect with journalists, editors, funders, and media leaders actively working on collaborative projects.",
        "color": "teal",
        "order": 128,
        "component": "BenefitCard",
        "link": ""
      },
      "cta_description": {
        "value": "Contact us to discuss sponsorship opportunities and receive a full prospectus.",
        "color": "cardinal",
        "order": 132,
        "component": "SectionDescription",
        "link": ""
      },
      "milestone_title": {
        "value": "Milestone event",
        "color": "teal",
        "order": 125,
        "component": "BenefitCard",
        "link": ""
      },
      "page_description": {
        "value": "Support the 10th anniversary Collaborative Journalism Summit and connect with 130+ leaders in collaborative journalism.",
        "color": "ink",
        "order": 121,
        "component": "PageDescription",
        "link": ""
      }
    },
    "schedule": {
      "page_headline": {
        "value": "Schedule",
        "color": "ink",
        "order": 100,
        "component": "PageHeadline",
        "link": ""
      },
      "inn_days_title": {
        "value": "Co-located with INN Days",
        "color": "green-dark",
        "order": 108,
        "component": "SectionTitle",
        "link": ""
      },
      "tuesday_label": {
        "value": "Tuesday, June 9",
        "color": "cardinal",
        "order": 106,
        "component": "DayLabel",
        "link": ""
      },
      "preliminary_label": {
        "value": "Preliminary schedule",
        "color": "teal",
        "order": 102,
        "component": "Badge",
        "link": ""
      },
      "preliminary_notice": {
        "value": "Session pitches will be accepted through Jan. 31, 2026. Session topics and speakers will be announced in spring 2026. ",
        "color": "ink",
        "order": 103,
        "component": "Notice",
        "link": ""
      }
    },
    "code_of_conduct": {
      "reporting_headline": {
        "value": "Reporting",
        "color": "ink",
        "order": 147,
        "component": "SectionHeadline",
        "link": ""
      },
      "unacceptable_headline": {
        "value": "Unacceptable behavior",
        "color": "cardinal",
        "order": 145,
        "component": "SectionHeadline",
        "link": ""
      },
      "page_description": {
        "value": "The Collaborative Journalism Summit is dedicated to providing a harassment-free experience for everyone.",
        "color": "ink",
        "order": 141,
        "component": "PageDescription",
        "link": ""
      },
      "consequences_headline": {
        "value": "Consequences",
        "color": "ink",
        "order": 149,
        "component": "SectionHeadline",
        "link": ""
      },
      "expected_items": {
        "value": "Participate authentically and actively\nExercise consideration and respect in your speech and actions\nAttempt collaboration before conflict\nRefrain from demeaning, discriminatory, or harassing behavior and speech\nBe mindful of your surroundings and fellow participants\nAlert conference organizers if you notice violations or someone in distress",
        "color": "teal",
        "order": 144,
        "component": "List",
        "link": ""
      }
    },
    "contact": {
      "twitter_description": {
        "value": "Follow us for summit updates and collaborative journalism news",
        "color": "ink",
        "order": 167,
        "component": "ContactCard",
        "link": ""
      },
      "twitter_label": {
        "value": "Twitter/X",
        "color": "ink",
        "order": 165,
        "component": "ContactCard",
        "link": ""
      },
      "organizer_headline": {
        "value": "About the organizers",
        "color": "ink",
        "order": 168,
        "component": "SectionHeadline",
        "link": ""
      },
      "ccm_url": {
        "value": "https://centerforcooperativemedia.org",
        "color": "teal",
        "order": 171,
        "component": "OrganizerCard",
        "link": ""
      },
      "twitter_value": {
        "value": "@CenterCoopMedia",
        "color": "ink",
        "order": 166,
        "component": "ContactCard",
        "link": ""
      },
      "ccm_name": {
        "value": "Center for Cooperative Media",
        "color": "teal",
        "order": 169,
        "component": "OrganizerCard",
        "link": ""
      },
      "page_description": {
        "value": "Have questions about the Collaborative Journalism Summit? We're here to help.",
        "color": "ink",
        "order": 161,
        "component": "PageDescription",
        "link": ""
      }
    }
  },
  "Contact": {
    "contact": {
      "twitter_description": {
        "value": "Follow us for summit updates and collaborative journalism news",
        "color": "ink",
        "order": 167,
        "component": "ContactCard",
        "link": ""
      },
      "organizer_headline": {
        "value": "About the organizers",
        "color": "ink",
        "order": 168,
        "component": "SectionHeadline",
        "link": ""
      },
      "inn_description": {
        "value": "A network of more than 450 nonprofit news organizations. INN supports, connects, and champions public service journalism.",
        "color": "cardinal",
        "order": 173,
        "component": "OrganizerCard",
        "link": ""
      },
      "twitter_label": {
        "value": "Twitter/X",
        "color": "ink",
        "order": 165,
        "component": "ContactCard",
        "link": ""
      },
      "email_description": {
        "value": "For general inquiries, sponsorship questions, and press requests",
        "color": "teal",
        "order": 164,
        "component": "ContactCard",
        "link": ""
      },
      "inn_name": {
        "value": "Institute for Nonprofit News",
        "color": "cardinal",
        "order": 172,
        "component": "OrganizerCard",
        "link": ""
      },
      "email_value": {
        "value": "summit@collaborativejournalism.org",
        "color": "teal",
        "order": 163,
        "component": "ContactCard",
        "link": ""
      },
      "email_label": {
        "value": "Email address",
        "color": "ink",
        "order": 162,
        "component": "ContactCard",
        "link": ""
      },
      "ccm_description": {
        "value": "A grant-funded program of the School of Communication and Media at Montclair State University. The Center grows and strengthens local journalism in New Jersey and beyond.",
        "color": "teal",
        "order": 170,
        "component": "OrganizerCard",
        "link": ""
      },
      "page_headline": {
        "value": "Contact us",
        "color": "ink",
        "order": 160,
        "component": "PageHeadline",
        "link": ""
      },
      "ccm_name": {
        "value": "Center for Cooperative Media",
        "color": "teal",
        "order": 169,
        "component": "OrganizerCard",
        "link": ""
      },
      "page_description": {
        "value": "Have questions about the Collaborative Journalism Summit? We're here to help.",
        "color": "ink",
        "order": 161,
        "component": "PageDescription",
        "link": ""
      },
      "twitter_value": {
        "value": "@CenterCoopMedia",
        "color": "ink",
        "order": 166,
        "component": "ContactCard",
        "link": ""
      },
      "inn_url": {
        "value": "https://inn.org",
        "color": "cardinal",
        "order": 174,
        "component": "OrganizerCard",
        "link": ""
      },
      "ccm_url": {
        "value": "https://centerforcooperativemedia.org",
        "color": "teal",
        "order": 171,
        "component": "OrganizerCard",
        "link": ""
      }
    }
  },
  "Register": {
    "register": {
      "email_label": {
        "value": "Email address",
        "color": "ink",
        "order": 202,
        "component": "FormLabel",
        "link": ""
      },
      "login_prompt": {
        "value": "Already have an account?",
        "color": "ink",
        "order": 206,
        "component": "Text",
        "link": ""
      },
      "submit_button": {
        "value": "Create account",
        "color": "teal",
        "order": 205,
        "component": "Button",
        "link": ""
      }
    }
  },
  "Code of Conduct": {
    "code_of_conduct": {
      "consequences_text": {
        "value": "Anyone asked to stop unacceptable behavior is expected to comply immediately. If a participant engages in unacceptable behavior, the conference organizers may take any action they deem appropriate, up to and including a temporary ban or permanent expulsion from the event without warning or refund.",
        "color": "ink",
        "order": 150,
        "component": "BodyText",
        "link": ""
      },
      "page_headline": {
        "value": "Code of conduct",
        "color": "ink",
        "order": 140,
        "component": "PageHeadline",
        "link": ""
      },
      "intro": {
        "value": "We are committed to creating a welcoming and inclusive environment for all participants, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, or technology choices.",
        "color": "ink",
        "order": 142,
        "component": "IntroText",
        "link": ""
      },
      "reporting_text": {
        "value": "If you experience or witness unacceptable behavior, or have any other concerns, please notify a conference organizer as soon as possible. You can reach us at summit@collaborativejournalism.org or speak with any staff member at the registration desk.",
        "color": "ink",
        "order": 148,
        "component": "BodyText",
        "link": ""
      },
      "unacceptable_items": {
        "value": "Intimidating, harassing, abusive, discriminatory, derogatory, or demeaning speech or actions\nHarmful or prejudicial verbal or written comments related to gender, gender identity, sexual orientation, race, religion, disability\nInappropriate use of nudity and/or sexual images\nDeliberate intimidation, stalking, or following\nSustained disruption of talks or other events\nUnwelcome physical contact or sexual attention\nAdvocating for or encouraging any of the above behaviors",
        "color": "cardinal",
        "order": 146,
        "component": "List",
        "link": ""
      },
      "expected_headline": {
        "value": "Expected behavior",
        "color": "teal",
        "order": 143,
        "component": "SectionHeadline",
        "link": ""
      },
      "consequences_headline": {
        "value": "Consequences",
        "color": "ink",
        "order": 149,
        "component": "SectionHeadline",
        "link": ""
      },
      "reporting_headline": {
        "value": "Reporting",
        "color": "ink",
        "order": 147,
        "component": "SectionHeadline",
        "link": ""
      },
      "expected_items": {
        "value": "Participate authentically and actively\nExercise consideration and respect in your speech and actions\nAttempt collaboration before conflict\nRefrain from demeaning, discriminatory, or harassing behavior and speech\nBe mindful of your surroundings and fellow participants\nAlert conference organizers if you notice violations or someone in distress",
        "color": "teal",
        "order": 144,
        "component": "List",
        "link": ""
      },
      "unacceptable_headline": {
        "value": "Unacceptable behavior",
        "color": "cardinal",
        "order": 145,
        "component": "SectionHeadline",
        "link": ""
      },
      "page_description": {
        "value": "Have questions about the Collaborative Journalism Summit? We're here to help.",
        "color": "ink",
        "order": 141,
        "component": "PageDescription",
        "link": ""
      }
    }
  },
  "Sponsors": {
    "sponsors": {
      "audience_title": {
        "value": "Engaged audience",
        "color": "teal",
        "order": 127,
        "component": "BenefitCard",
        "link": ""
      },
      "open_description": {
        "value": "Be among the first to support the 10th anniversary summit. Sponsors will be recognized here as they are confirmed.",
        "color": "ink",
        "order": 123,
        "component": "Notice",
        "link": ""
      },
      "custom_description": {
        "value": "Interested in sponsoring a specific element of the summit? We offer custom packages for:",
        "color": "ink",
        "order": 134,
        "component": "SectionDescription",
        "link": ""
      },
      "milestone_description": {
        "value": "Be part of our 10th anniversary celebration - a landmark moment in the collaborative journalism movement.",
        "color": "teal",
        "order": 126,
        "component": "BenefitCard",
        "link": ""
      },
      "audience_description": {
        "value": "Connect with journalists, editors, funders, and media leaders actively working on collaborative projects.",
        "color": "teal",
        "order": 128,
        "component": "BenefitCard",
        "link": ""
      },
      "cta_headline": {
        "value": "Ready to sponsor?",
        "color": "cardinal",
        "order": 131,
        "component": "SectionHeadline",
        "link": ""
      },
      "custom_headline": {
        "value": "Custom sponsorship opportunities",
        "color": "ink",
        "order": 133,
        "component": "SectionHeadline",
        "link": ""
      },
      "cta_description": {
        "value": "Contact us to discuss sponsorship opportunities and receive a full prospectus.",
        "color": "cardinal",
        "order": 132,
        "component": "SectionDescription",
        "link": ""
      },
      "exposure_description": {
        "value": "Co-located with INN Days means additional visibility to the nonprofit news community.",
        "color": "teal",
        "order": 130,
        "component": "BenefitCard",
        "link": ""
      },
      "page_description": {
        "value": "Support the 10th anniversary Collaborative Journalism Summit and connect with 130+ leaders in collaborative journalism.",
        "color": "ink",
        "order": 121,
        "component": "PageDescription",
        "link": ""
      },
      "milestone_title": {
        "value": "Milestone event",
        "color": "teal",
        "order": 125,
        "component": "BenefitCard",
        "link": ""
      },
      "exposure_title": {
        "value": "Dual-event exposure",
        "color": "teal",
        "order": 129,
        "component": "BenefitCard",
        "link": ""
      },
      "open_label": {
        "value": "Sponsorships now open",
        "color": "teal",
        "order": 122,
        "component": "Badge",
        "link": ""
      },
      "page_headline": {
        "value": "Dashboard",
        "color": "ink",
        "order": 120,
        "component": "PageHeadline",
        "link": ""
      },
      "why_sponsor_headline": {
        "value": "Why sponsor the summit?",
        "color": "ink",
        "order": 124,
        "component": "SectionHeadline",
        "link": ""
      }
    }
  },
  "Dashboard": {
    "dashboard": {
      "signout_button": {
        "value": "Sign out",
        "color": "cardinal",
        "order": 212,
        "component": "Button",
        "link": ""
      },
      "welcome_message": {
        "value": "Welcome back!",
        "color": "ink",
        "order": 211,
        "component": "WelcomeText",
        "link": ""
      },
      "page_headline": {
        "value": "Dashboard",
        "color": "ink",
        "order": 210,
        "component": "PageHeadline",
        "link": ""
      }
    }
  }
};

// Timeline data (sorted by order)
export const timeline = [
  {
    "year": "2017",
    "location": "Montclair, NJ",
    "theme": "The Beginning",
    "link": "https://www.montclair.edu/college-of-communication-and-media/2017/06/07/18156_collaborative-journalism-summit-highlights-new-ideas-for-impactful-reporting/",
    "color": "teal",
    "order": 40
  },
  {
    "year": "2018",
    "location": "Montclair, NJ",
    "theme": "Building Bridges",
    "link": "https://collaborativejournalism.org/2018summit/",
    "color": "teal",
    "order": 44
  },
  {
    "year": "2019",
    "location": "Philadelphia, PA",
    "theme": "People Over Projects",
    "link": "https://collaborativejournalism.org/cjs2019/",
    "color": "cardinal",
    "order": 48
  },
  {
    "year": "2020",
    "location": "Virtual",
    "theme": "Adapting Together",
    "link": "https://collaborativejournalism.org/cjs2020/",
    "color": "ink",
    "order": 52
  },
  {
    "year": "2021",
    "location": "Virtual",
    "theme": "Removing Barriers",
    "link": "https://collaborativejournalism.org/cjs2021/",
    "color": "ink",
    "order": 56
  },
  {
    "year": "2022",
    "location": "Chicago, IL",
    "theme": "Building to Last",
    "link": "https://collaborativejournalism.org/cjs2022/",
    "color": "green-dark",
    "order": 60
  },
  {
    "year": "2023",
    "location": "Washington, D.C.",
    "theme": "Building Frameworks",
    "link": "https://collaborativejournalism.org/cjs2023/",
    "color": "teal",
    "order": 64
  },
  {
    "year": "2024",
    "location": "Detroit, MI",
    "theme": "Global Impact",
    "link": "https://collaborativejournalism.org/cjs2024/",
    "color": "cardinal",
    "order": 68
  },
  {
    "year": "2025",
    "location": "Denver, CO",
    "theme": "Partnerships with Purpose",
    "link": "https://collaborativejournalism.org/cjs2025/",
    "color": "green-dark",
    "order": 72
  },
  {
    "year": "2026",
    "location": "Chapel Hill, NC",
    "theme": "10th Anniversary",
    "link": "",
    "color": "gold",
    "order": 76
  }
];

// Stats data (sorted by order)
export const stats = [
  {
    "id": "summits",
    "value": "10",
    "label": "Summits",
    "color": "teal",
    "order": 30
  },
  {
    "id": "cities",
    "value": "7",
    "label": "Cities",
    "color": "teal",
    "order": 32
  },
  {
    "id": "attendees",
    "value": "1500+",
    "label": "Attendees",
    "color": "teal",
    "order": 34
  },
  {
    "id": "mission",
    "value": "1",
    "label": "Mission",
    "color": "teal",
    "order": 36
  }
];

// Helper function to get content value
export function getContent(section, field, defaultValue = '') {
  return sections[section]?.[field]?.value ?? defaultValue;
}

// Helper function to get content with metadata
export function getContentMeta(section, field) {
  return sections[section]?.[field] ?? null;
}

// Helper function to get all content for a section
export function getSection(sectionName) {
  return sections[sectionName] ?? {};
}

// Helper function to get content for a specific page
export function getPageContent(pageName) {
  return byPage[pageName] ?? {};
}

// Color class mapping
const colorClasses = {
  teal: { text: 'text-brand-teal', bg: 'bg-brand-teal', border: 'border-brand-teal' },
  cardinal: { text: 'text-brand-cardinal', bg: 'bg-brand-cardinal', border: 'border-brand-cardinal' },
  'green-dark': { text: 'text-brand-green-dark', bg: 'bg-brand-green-dark', border: 'border-brand-green-dark' },
  ink: { text: 'text-brand-ink', bg: 'bg-brand-ink', border: 'border-brand-ink' },
  cream: { text: 'text-brand-cream', bg: 'bg-brand-cream', border: 'border-brand-cream' },
  gold: { text: 'text-brand-gold', bg: 'bg-brand-gold', border: 'border-brand-gold' },
  white: { text: 'text-white', bg: 'bg-white', border: 'border-white' },
};

export function getColorClass(colorName, type = 'text') {
  return colorClasses[colorName]?.[type] ?? '';
}

// Generation metadata
export const metadata = {
  generatedAt: '2025-12-15T16:46:22.121Z',
  recordCount: 146,
  sections: ["footer","schedule","login","details","contact","stats","register","navbar","code_of_conduct","timeline","sponsors","expect","history","dashboard"],
  pages: ["Global","Schedule","Login","Home","Contact","Register","Code of Conduct","Sponsors","Dashboard"]
};

export default {
  sections,
  byPage,
  timeline,
  stats,
  getContent,
  getContentMeta,
  getSection,
  getPageContent,
  getColorClass,
  metadata
};
