/**
 * Updates/News data generated from Airtable
 *
 * Generated: 2026-01-05T18:58:09.527Z
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * To update:
 * 1. Edit the "Updates" table in Airtable
 * 2. Run: npm run generate-updates
 * 3. Review changes and commit
 *
 * Each update has a unique slug for shareable URLs:
 * summit.collaborativejournalism.org/updates/[slug]
 */

// All updates (sorted by date, newest first)
export const updates = [
  {
    "slug": "pitch-deadline-january-31",
    "type": "deadline",
    "featured": false,
    "title": "Session pitch deadline: January 31",
    "summary": "Final call for session proposals. Pitch a panel, workshop, or lightning talk to help shape the CJS2026 program.",
    "content": "**The deadline for CJS2026 session pitches is January 31, 2026.**\n\nWe're looking for proposals that showcase real-world collaborative journalism — successes, challenges, and lessons learned.\n\n**Submit your pitch:**\nEmail summit@collaborativejournalism.org with your proposal by January 31.",
    "date": "2026-01-31",
    "category": "Deadlines",
    "countdown": true,
    "cta": {
      "text": "Contact us to pitch",
      "url": "/contact",
      "external": false
    },
    "color": "cardinal",
    "visible": true,
    "order": 3
  },
  {
    "slug": "cjs2026-pittsburgh",
    "type": "announcement",
    "featured": true,
    "title": "CJS2026 heads to Pittsburgh, Pennsylvania",
    "summary": "The Steel City becomes the home for our 10th anniversary summit on June 8-9, 2026.",
    "content": "For the 10th anniversary Collaborative Journalism Summit, we're heading to Pittsburgh, Pennsylvania.\n\n**Dates: June 8-9, 2026**\n- **Monday, June 8** — Full day of sessions plus evening dinner\n- **Tuesday, June 9** — Morning workshops\n\n**Co-located with INN Days**\nStay for INN Days (June 9-11) and get even more value from your trip.",
    "date": "2026-01-05",
    "category": "Location",
    "countdown": false,
    "cta": {
      "text": "See event details",
      "url": "/#details",
      "external": false
    },
    "color": "teal",
    "visible": true,
    "order": 999
  },
  {
    "slug": "session-pitches-open",
    "type": "announcement",
    "featured": true,
    "title": "Session pitches now open for CJS2026",
    "summary": "We're accepting proposals for panels, workshops, and lightning talks. Share your collaborative journalism expertise with 150 practitioners, funders, and media leaders.",
    "content": "The 10th anniversary Collaborative Journalism Summit is taking shape, and we need your help to build the program.\n\n**What we're looking for:**\n- **Panels** (45-60 min) — Moderated discussions with 3-4 speakers\n- **Workshops** (90 min) — Hands-on learning sessions with practical takeaways\n- **Lightning talks** (10 min) — Quick case studies or lessons learned\n\n**Topics of interest:**\n- Sustainability models for news collaboratives\n- Technology and tools that enable collaboration\n- Measuring the impact of collaborative journalism\n- Building and maintaining trust with partners\n- Regional and hyperlocal collaboration strategies\n\n**Deadline: January 31, 2026**\n\nContact us at summit@collaborativejournalism.org with your proposal.",
    "date": "2026-01-02",
    "category": "Call for proposals",
    "countdown": false,
    "cta": {
      "text": "Contact us to pitch",
      "url": "/contact",
      "external": false
    },
    "color": "teal",
    "visible": true,
    "order": 1
  },
  {
    "slug": "knight-foundation-presenting-sponsor",
    "type": "announcement",
    "featured": true,
    "title": "Knight Foundation joins as presenting sponsor",
    "summary": "We're honored to welcome Knight Foundation as the presenting sponsor of CJS2026, continuing their commitment to strengthening journalism through collaboration.",
    "content": "Knight Foundation has joined CJS2026 as the presenting sponsor, marking a decade of their investment in the collaborative journalism movement.\n\nSince the earliest days of the Collaborative Journalism Summit, Knight Foundation has been a champion of the idea that journalism is stronger when newsrooms work together.\n\nFor information about sponsoring CJS2026, visit the sponsors page or contact summit@collaborativejournalism.org.",
    "date": "2025-12-18",
    "category": "Sponsors",
    "countdown": false,
    "cta": {
      "text": "Learn about sponsoring",
      "url": "/sponsors",
      "external": false
    },
    "color": "cardinal",
    "visible": true,
    "order": 2
  },
  {
    "slug": "decade-of-collaborative-journalism",
    "type": "story",
    "featured": false,
    "title": "A decade of proving journalism is stronger together",
    "summary": "Since 2017, CJS has grown from 161 attendees in Montclair to 1,981 unique participants across 6 cities.",
    "content": "In 2017, 161 people gathered at Montclair State University for an unconventional idea: What if competing newsrooms actually worked together?\n\nTen years later, collaborative journalism has grown from an experiment into standard practice.\n\n**By the numbers:**\n- **10** summits since 2017\n- **6** cities (Pittsburgh will be #7!)\n- **2,569** total registrations\n- **1,981** unique attendees\n- **1** mission: journalism is stronger together",
    "date": "2025-12-15",
    "category": "10th anniversary",
    "countdown": false,
    "cta": {
      "text": "Explore our full history",
      "url": "/#history",
      "external": false
    },
    "color": "green-dark",
    "visible": true,
    "order": 4
  },
  {
    "slug": "registration-coming-soon",
    "type": "announcement",
    "featured": false,
    "title": "Registration opens mid-January 2026",
    "summary": "Space is limited to 150 attendees — register early to secure your spot and book travel.",
    "content": "Registration for CJS2026 opens mid-January 2026 — around the same time we start accepting session pitches.\n\n**Limited capacity:**\nWe're keeping CJS2026 intentionally small — 150 attendees — to foster the kind of connections that lead to real partnerships.\n\n**What's included:**\n- Full access to all CJS2026 sessions (June 8-9)\n- Monday evening dinner and celebration\n- Coffee, snacks, and lunch\n- Access to the CJS community Slack workspace\n- Materials and resources from sessions\n\n**Questions?**\nEmail summit@collaborativejournalism.org with any registration questions.",
    "date": "2025-11-15",
    "category": "Registration",
    "countdown": false,
    "cta": {
      "text": "Get email updates",
      "url": "/",
      "external": false
    },
    "color": "teal",
    "visible": true,
    "order": 10
  }
];

// Helper functions
export function getUpdateBySlug(slug) {
  return updates.find(u => u.slug === slug) || null;
}

export function getFeaturedUpdates() {
  return updates.filter(u => u.featured);
}

export function getRecentUpdates(limit = 5) {
  return updates.slice(0, limit);
}

export function getUpdatesByCategory(category) {
  return updates.filter(u => u.category.toLowerCase() === category.toLowerCase());
}

// Calculate days until a date
export function getDaysUntil(dateString) {
  const target = new Date(dateString);
  const now = new Date();
  const diff = target - now;
  return Math.max(0, Math.ceil(diff / (1000 * 60 * 60 * 24)));
}

// Generation metadata
export const metadata = {
  generatedAt: '2026-01-05T18:58:09.527Z',
  totalUpdates: 6,
  featuredCount: 3,
  categories: ["Deadlines","Location","Call for proposals","Sponsors","10th anniversary","Registration"],
};

export default updates;
